### ISSUE TITLE
rt0 irq handler destroys system mode LR register

### ISSUE THREAD

**Issue by LunarLambda** [Lokathor/gba-from-scratch#11]
https://github.com/Lokathor/gba-from-scratch/blob/main/src/rt0.S#L110-L114

**Comment by ketsuban** [comment]
Triage: commit c122a04 rendered this issue obsolete by rewriting the offending code. (At the time the link provided referred to [this code](https://github.com/Lokathor/gba-from-scratch/blob/ace5f6e6f13c4bf59369836d465fd6dd1c8558a4/src/rt0.S#L110-L114), but [the revised code](https://github.com/Lokathor/gba-from-scratch/blob/03f91111620fb94b7f98d1d55ee586475cc876ba/src/rt0.S#L97-L101) correctly stashes the value of registers including `lr`.) It can be closed.

**Comment by Lokathor** [comment]
oh right i didn't close the issue
