### ISSUE TITLE
Tutorial `2. Rust Setup` Requires using nightly

### ISSUE THREAD

**Issue by Hpmason** [Lokathor/gba-from-scratch#13]
I'm going through the tutorial series and noticed that the rust setup doesn't mention switching to nightly, either through `rustup override` command or a `rust-toolchain.toml` file. 

If using a stable toolchain the code will not compile and give the following error:
```
error[E0463]: can't find crate for `core`
  |
  = note: the `thumbv4t-none-eabi` target may not be installed
  = help: consider downloading the target with `rustup target add thumbv4t-none-eabi`

For more information about this error, try `rustc --explain E0463`.
error: could not compile `gba-from-scratch` due to previous error
```
Which is misleading since there isn't a thumbv4t-none-eabi target with rustup

**Comment by Lokathor** [comment]
Does https://github.com/Lokathor/gba-from-scratch/commit/4cb237e05e3f4e7269b84f3b71a5b96c1ff3dc63 look good?

**Comment by Hpmason** [comment]
Yeah, that's great!
